format = """
$env_var\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[env_var]
variable = "SHPOOL_SESSION_NAME"
format = "[$env_value]($style) "
style = "bright-white"      # or "fg:#ffffff" for exact white


[directory]
style = "bold italic bright-cyan"

[character]
success_symbol = "[❯](bright-red)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](white)"

[git_branch]
format = "[$branch]($style)"
style = "bright-green"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-orange"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-blue"
