format = """
$custom.hanni\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$python\
$character"""

[custom.hanni]
command = "echo I love hanni"
when = "true"
shell = ["bash", "--norc", "--noprofile"]

# right_format = "${env_shpool}"
#
# [env_var.shpool]
# variable = "SHPOOL_SESSION_NAME"
# format = "[shpool:$env_value ]($style)"
# style = "bold green"
# default = ""      # hide if not in shpool

[directory]
style = "bold italic bright-cyan"

[character]
success_symbol = "[❯](bright-red)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](white)"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"
